export const REGULAR_ENEMY_FIRE_INTERVAL_MS = 1300;
export const STRAIGHT_ENEMY_HP = 2;
export const SWAY_ENEMY_HP = 3;
export const HEAVY_ENEMY_HP = 7;

export const DEFAULT_HEAVY_BULLET_COUNT = 4;
export const FINAL_WAVE_HEAVY_BULLET_COUNT = 3;
export const DEFAULT_HEAVY_FIRE_INTERVAL_MS = 1050;
export const FINAL_WAVE_HEAVY_FIRE_INTERVAL_MS = 1350;
