export const CLEAR_WARP_PLAYER_DELAY_MS = 650;
export const CLEAR_WARP_PLAYER_DURATION_MS = 1450;
export const CLEAR_WARP_RING_FADE_IN_DELAYS_MS = [520, 340, 160] as const;
export const CLEAR_WARP_RING_FADE_IN_DURATION_MS = 360;
export const CLEAR_WARP_RING_PASS_DELAYS_MS = [1480, 1180, 920] as const;
export const CLEAR_WARP_RING_EXPAND_DURATION_MS = 460;
export const CLEAR_WARP_RING_GROW_FADE_OUT_DURATION_MS =
  CLEAR_WARP_RING_EXPAND_DURATION_MS;
export const CLEAR_WARP_GATE_FADE_START_MS = 2350;
export const CLEAR_WARP_GATE_FADE_DURATION_MS = 650;
export const CLEAR_BONUS_ROUTE_DELAY_MS = 4500;
